end2end_eval:
  metrics:
    text_block:
      metric:
        - Edit_dist
    display_formula:
      metric:
        - Edit_dist
    table:
      metric:
        - TEDS
        - Edit_dist
    reading_order:
      metric:
        - Edit_dist
  dataset:
    dataset_name: end2end_dataset
    ground_truth:
      data_path: /tmp/new_annotations/single_gt.json
    prediction:
      data_path: /tmp/new_annotations/new预标注/outdata_mds
    match_method: quick_match
